FROM nginx:1.25

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf.template nginx.conf.template_local /etc/nginx/conf.d/

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
